scanner:
    diff_only: False  # If False, the entire file touched by the Pull Request is scanned for errors. If True, only the diff is scanned.
    linter: flake8

flake8:
    max-line-length: 120
    ignore:
        - W504  # line break after binary operator
        - E731  # do not assign a lambda expression, use a def
        - C406  # Unnecessary list literal - rewrite as a dict literal.
        - E741  # ambiguous variable name

no_blank_comment: True  # If True, no comment is made on PR without any errors.
descending_issues_order: False  # If True, PEP 8 issues in message will be displayed in descending order of line numbers in the file

message:  # Customize the comment made by the bot
    opened:  # Messages when a new PR is submitted
        header: "@{name}, my friend! There is something you should fix. "
                # The keyword {name} is converted into the author's username
    updated:  # Messages when new commits are added to the PR
        header: "Thanks for update, @{name}! "
    no_errors: "There are currently no PEP 8 issues detected in this Pull Request. Cheers! :beers: "