UnslothTrainingArguments:
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 4
  warmup_ratio: 0.1
  num_train_epochs: 10
  learning_rate: 0.0002 #2e-4
  logging_steps: 1
  optim: "adamw_8bit"
  weight_decay: 0.01
  lr_scheduler_type: "linear"
  seed: 3407
  save_strategy: "epoch"


PEFTParams:
  r: 16
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj",
                   "gate_proj", "up_proj", "down_proj",]
  lora_alpha: 16
  lora_dropout: 0
  bias: "none"
  use_gradient_checkpointing: "unsloth"
  random_state: 3407
  use_rslora: false
  loftq_config: null
