ModelConfig:
  max_seq_length: 2048
  dtype: null
  load_in_4bit: true


UnslothTrainingArguments:
  per_device_train_batch_size: 30
  gradient_accumulation_steps: 2
  warmup_ratio: 0.1
  num_train_epochs: 5
  learning_rate: 0.00005 #5e-5
  embedding_learning_rate: 0.000005 #5e-6
  optim: "adamw_8bit"
  weight_decay: 0.0
  lr_scheduler_type: "cosine"
  seed: 3407
  logging_steps: 1
  save_strategy: "epoch"
  do_eval: true
  eval_strategy: "epoch"
  eval_steps: 1
  eval_on_start: true


PEFTParams:
  r: 128
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj",
                   "gate_proj", "up_proj", "down_proj",
                   "embed_tokens", "lm_head"]
  lora_alpha: 32
  lora_dropout: 0
  bias: "none"
  use_gradient_checkpointing: "unsloth"
  random_state: 3407
  use_rslora: true
  loftq_config: null


Additional:
  unfreeze_embeddings: false